services:
  orcaslicer:
    build:
      context: .
      args:
        APP: orcaslicer
    container_name: webtop-orcaslicer
    hostname: webtop-orcaslicer
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Rome
      - SUBFOLDER=/
      - TITLE=OrcaSlicer
    volumes:
      - orcaslicer-config:/config
      - shared_data:/shared
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: 2gb
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
    networks:
      - webtop-net

  freecad:
    build:
      context: .
      args:
        APP: freecad
    container_name: webtop-freecad
    hostname: webtop-freecad
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Rome
      - SUBFOLDER=/
      - TITLE=FreeCAD
    volumes:
      - freecad-config:/config
      - shared_data:/shared
    ports:
      - 3002:3000
      - 3003:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: 2gb
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
    networks:
      - webtop-net

volumes:
  orcaslicer-config:
  freecad-config:
  shared_data:

networks:
  webtop-net:
    driver: bridge
