services:
  webtop:
    image: webtop-kde:latest
    container_name: webtop-kde
    hostname: webtop-kde
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Rome
      - SUBFOLDER=/
      - TITLE=WebTop
    volumes:
      - /home/Stefano/webtop-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri
    shm_size: 2gb
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
